title: Anthony Joseph Ruffa
description: "Follower of Jesus Christ.<br />Software Engineer.<br />Pittsburgh Sports Fan."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  anthonyjruffa
stackoverflow_username: anthonyjruffa
linkedin_username: anthonyjruffa


# Build settings
markdown: kramdown
theme: minima

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
